// AETHORIA: RIFT WARS — Character Definitions

export const ELEMENTS = {
  FIRE:      { name: 'Fire',      color: '#FF4500', reacts: { ICE: 'steam',      WATER: 'evaporate', NATURE: 'burn'       } },
  ICE:       { name: 'Ice',       color: '#87CEEB', reacts: { FIRE: 'steam',     WATER: 'freeze',    LIGHTNING: 'shatter' } },
  WIND:      { name: 'Wind',      color: '#E0E0E0', reacts: { FIRE: 'wildfire',  ICE: 'blizzard',    LIGHTNING: 'storm'   } },
  EARTH:     { name: 'Earth',     color: '#8B6914', reacts: { WATER: 'mud',      LIGHTNING: 'conduct', FIRE: 'ash'        } },
  LIGHT:     { name: 'Light',     color: '#FFD700', reacts: { SHADOW: 'annihilate', VOID: 'expose',  ICE: 'prism'         } },
  SHADOW:    { name: 'Shadow',    color: '#4B0082', reacts: { LIGHT: 'annihilate', FIRE: 'smoke',    VOID: 'corrupt'      } },
  LIGHTNING: { name: 'Lightning', color: '#FFFF00', reacts: { WATER: 'electrify', EARTH: 'conduct', ICE: 'shatter'       } },
  WATER:     { name: 'Water',     color: '#1E90FF', reacts: { FIRE: 'evaporate', LIGHTNING: 'electrify', ICE: 'freeze'   } },
  NATURE:    { name: 'Nature',    color: '#228B22', reacts: { FIRE: 'burn',       WATER: 'overgrow',  SHADOW: 'corrupt'   } },
  TIME:      { name: 'Time',      color: '#9370DB', reacts: { VOID: 'collapse',   LIGHTNING: 'accelerate', SHADOW: 'freeze_time' } },
  VOID:      { name: 'Void',      color: '#6600cc', reacts: { LIGHT: 'expose',    TIME: 'collapse',   ALL: 'null'         } },
  MAGMA:     { name: 'Magma',     color: '#CC4400', reacts: { WATER: 'obsidian',  ICE: 'melt',        EARTH: 'erupt'      } },
  AETHER:    { name: 'Aether',    color: '#FFFFFF', reacts: { ALL: 'override' } },
};

// ─── CHARACTER DEFINITIONS ────────────────────────────────────────────────────
// Palette A-H maps to pal[0-7]. '.' = transparent, 'I' = black outline (#000).
export const CHARACTERS = {

  // ── 1. NEON RYU ──────────────────────────────────────────────────────────────
  NEON_RYU: {
    id: 'NEON_RYU',
    name: 'Neon Ryu',
    element: 'LIGHTNING',
    title: 'The Electric Fist',
    weight: 100, speed: 10, jumpStrength: 19, airSpeed: 9, fallSpeed: 10,
    description: 'A street brawler who absorbed a rift surge into his fists. Neon Ryu punches reality itself.',
    lore: `Once an underground fighter in the neon-lit ruins of Voltcity, Ryu touched a crackling rift tear with his bare hands.
The lightning didn't kill him — it became him.
His fists now carry the force of a thunderstorm. Every punch echoes with the sound of a world cracking open.
He fights to close the rift before it devours the only city he ever called home.`,
    unlockCondition: 'default',
    // A=dark-navy gi  B=mid-blue gi  C=skin  D=skin-shadow  E=lightning-yellow  F=white
    // G=grey-hair  H=dark-grey-hair  J=blue-orb  K=dark-pants  L=orb-glow  M=red-headband
    // N=hair-highlight  O=boot-black  P=belt-grey
    palette: [
      '#1e2888','#3344cc','#e8c090','#b07840','#88aaff','#ffffff',
      '#cccccc','#888888','#5577ff','#080e44','#aaccff','#cc1100',
      '#eeeeee','#111122','#999999','#555566',
    ],
    sprite: {
      idle: [
        '.....INNNNNI........',
        '....INGFFFFNI.......',
        '....INGFFFFNI.......',
        '....IMMMMMMI........',
        '....ICCCCCCCI.......',
        '...ICDI..IDCI.......',
        '....ICCCCCCI........',
        '.....IICCCII........',
        '..IBBCCCCCBBII......',
        '.IBBBCCCCCBBBII.....',
        'JIBBBCCCCCBBBIJ.....',
        'JIBBBBBBBBBBBIJ.....',
        '.IBBBBBBBBBBBII.....',
        '.IBBPHHHHPHBBII.....',
        '.IKKKKKKKKKKKI......',
        '.IKKKKKKKKKKKI......',
        '.IKKKKI.IKKKI.......',
        'LJKKKI..IKKKJL......',
        'LJJJKI..IKKJJL......',
        '.IBBKI..IKKBBI......',
        '.IOOKKI.IKKOOII.....',
        '.IOOOKI.IKOOOI......',
        '..IOII..IIOOI.......',
      ],
    },
    moves: {
      jab:      { damage: 4,  kb: 3,  kbAngle: 30,  startup: 2,  active: 2, recovery: 7,  element: 'LIGHTNING', type: 'melee' },
      ftilt:    { damage: 9,  kb: 7,  kbAngle: 20,  startup: 6,  active: 3, recovery: 12, element: 'LIGHTNING', type: 'melee' },
      utilt:    { damage: 8,  kb: 6,  kbAngle: 85,  startup: 6,  active: 3, recovery: 11, element: 'LIGHTNING', type: 'melee' },
      dtilt:    { damage: 7,  kb: 5,  kbAngle: 15,  startup: 5,  active: 2, recovery: 10, element: 'LIGHTNING', type: 'melee' },
      fsmash:   { damage: 22, kb: 16, kbAngle: 25,  startup: 15, active: 3, recovery: 22, element: 'LIGHTNING', type: 'melee', charged: true },
      usmash:   { damage: 18, kb: 14, kbAngle: 90,  startup: 13, active: 4, recovery: 20, element: 'LIGHTNING', type: 'melee', charged: true },
      dsmash:   { damage: 16, kb: 12, kbAngle: 45,  startup: 12, active: 5, recovery: 19, element: 'LIGHTNING', type: 'melee', charged: true },
      nair:     { damage: 8,  kb: 6,  kbAngle: 45,  startup: 5,  active: 4, recovery: 11, element: 'LIGHTNING', type: 'aerial' },
      fair:     { damage: 12, kb: 9,  kbAngle: 30,  startup: 8,  active: 3, recovery: 15, element: 'LIGHTNING', type: 'aerial' },
      bair:     { damage: 11, kb: 8,  kbAngle: 40,  startup: 7,  active: 2, recovery: 13, element: 'LIGHTNING', type: 'aerial' },
      uair:     { damage: 10, kb: 8,  kbAngle: 80,  startup: 7,  active: 3, recovery: 13, element: 'LIGHTNING', type: 'aerial' },
      dair:     { damage: 13, kb: 10, kbAngle: 270, startup: 10, active: 2, recovery: 17, element: 'LIGHTNING', type: 'spike' },
      neutralB: { damage: 9,  kb: 5,  kbAngle: 15,  startup: 10, active: 40, recovery: 8, element: 'LIGHTNING', type: 'projectile', name: 'Thunder Orb' },
      sideB:    { damage: 15, kb: 11, kbAngle: 20,  startup: 9,  active: 3, recovery: 18, element: 'LIGHTNING', type: 'dash', name: 'Volt Dash' },
      upB:      { damage: 12, kb: 9,  kbAngle: 90,  startup: 8,  active: 4, recovery: 28, element: 'LIGHTNING', type: 'recovery', name: 'Thunder Ascent' },
      downB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 14, active: 0, recovery: 18, element: 'LIGHTNING', type: 'counter', name: 'Static Guard' },
      ultimate: { damage: 40, kb: 22, kbAngle: 45,  startup: 18, active: 8, recovery: 38, element: 'LIGHTNING', type: 'ultimate', name: 'Storm Breaker', desc: 'Erupts in a full-screen lightning cage, stunning all.', ultimateCost: 100 },
    },
    story: {
      intro: `The rift opened above Voltcity at midnight. By morning, half the streets were gone. Ryu was still standing — with the storm inside him.`,
      chapters: [
        { title: 'Current Situation', text: 'Ryu finds the rift has spread underground, crackling through the city\'s power grid. Every time it pulses, more people disappear.' },
        { title: 'Charged Up', text: 'He discovers his powers are amplified near the rift — dangerously so. One punch nearly levels a building.' },
        { title: 'Old Rivals', text: 'VHS Viper appears, hunting the same rift energy for herself. They clash before realizing they need each other.' },
        { title: 'The Power Grid', text: 'Ryu channels his lightning into the city\'s dying grid, keeping the lights on and the people alive. It nearly burns him out.' },
        { title: 'Storm Warning', text: 'Shadow Beast attacks. It feeds on electromagnetic energy — and Ryu is full of it. He\'s a walking beacon.' },
        { title: 'Overload', text: 'Ryu pushes past his limits, absorbing a rift pulse directly. He glows like a sun. He knows he has one shot.' },
        { title: 'Static King', text: 'The ultimate detonates. Rift energy shatters across Voltcity. Ryu stands in the smoking crater, drained but alive.' },
        { title: 'After the Storm', text: 'The city hums back to life. Ryu sits on a rooftop, watching the lights flicker on one by one. He smiles.' },
      ],
      ending: `Voltcity glows again. Ryu didn't save it with strength alone — he saved it by becoming the power it needed. The storm inside him is quiet now. He wonders how long that'll last.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Static Recolor', 'Golden Circuit'],
  },

  // ── 2. VHS VIPER ─────────────────────────────────────────────────────────────
  VHS_VIPER: {
    id: 'VHS_VIPER',
    name: 'VHS Viper',
    element: 'SHADOW',
    title: 'The Ghost Tape',
    weight: 78, speed: 13, jumpStrength: 21, airSpeed: 12, fallSpeed: 7,
    description: 'An assassin encoded on magnetic tape. She phases in and out of reality like a corrupted signal.',
    lore: `Nobody knows who she was before. The tape is all that remains — a VHS cassette found in the rubble of a rift collapse.
When played, she steps out of the screen, fully formed, with no memory and no mercy.
She hunts rift energy to find the original recording — the one with her real face on it.
Every target she eliminates brings her one frame closer to the truth.`,
    unlockCondition: 'default',
    // A=dark-purple suit  B=mid-purple  C=visor-glass  D=visor-dark  E=magenta-accent
    // F=white  G=grey-suit  H=suit-shadow  J=pink-glow  K=black-detail  L=light-purple
    // M=visor-glow  N=glove  O=boot-dark  P=belt-accent
    palette: [
      '#330044','#5500aa','#ee88ff','#aa44cc','#ff00ff','#ffffff',
      '#666677','#220033','#ff44ff','#110022','#cc88ff','#ff88ff',
      '#ddaaff','#221133','#442266','#993388',
    ],
    sprite: {
      idle: [
        '....IKKKKKKI........',
        '...IKKGGGGKKI.......',
        '..IKGCMMMCGKKI......',
        '..IKGCDDDCGKKI......',
        '..IKGCMMMCGKKI......',
        '...IKKGGGGKKI.......',
        '....IIAAAIII........',
        '...IBAAAAABII.......',
        '..IBAAAAAAAABBI.....',
        '..IBAAAAAAAABBI.....',
        '..IBAAAAAAAABBI.....',
        '..IBBBPPPBBBII......',
        '..IBBBBBBBII........',
        '..IBBBB.BBBBII......',
        '..IBBBBI.BBBBI......',
        '.IOBBBBI.IBBBOI.....',
        '.IOBBBBI.IBBBOI.....',
        '.IOOBBBI.IBBBOOI....',
        '..IOOBII.IIBOOI.....',
        '...IOII...IIOI......',
      ],
    },
    moves: {
      jab:      { damage: 3,  kb: 2,  kbAngle: 25,  startup: 2,  active: 2, recovery: 6,  element: 'SHADOW', type: 'melee' },
      ftilt:    { damage: 8,  kb: 6,  kbAngle: 20,  startup: 5,  active: 2, recovery: 10, element: 'SHADOW', type: 'melee' },
      utilt:    { damage: 7,  kb: 5,  kbAngle: 88,  startup: 5,  active: 2, recovery: 10, element: 'SHADOW', type: 'melee' },
      dtilt:    { damage: 6,  kb: 4,  kbAngle: 10,  startup: 4,  active: 3, recovery: 9,  element: 'SHADOW', type: 'melee' },
      fsmash:   { damage: 19, kb: 13, kbAngle: 20,  startup: 14, active: 2, recovery: 20, element: 'SHADOW', type: 'melee', charged: true },
      usmash:   { damage: 16, kb: 11, kbAngle: 85,  startup: 12, active: 3, recovery: 18, element: 'SHADOW', type: 'melee', charged: true },
      dsmash:   { damage: 14, kb: 10, kbAngle: 30,  startup: 11, active: 4, recovery: 17, element: 'SHADOW', type: 'melee', charged: true },
      nair:     { damage: 7,  kb: 5,  kbAngle: 40,  startup: 4,  active: 5, recovery: 10, element: 'SHADOW', type: 'aerial' },
      fair:     { damage: 11, kb: 8,  kbAngle: 25,  startup: 7,  active: 2, recovery: 13, element: 'SHADOW', type: 'aerial' },
      bair:     { damage: 10, kb: 7,  kbAngle: 35,  startup: 6,  active: 3, recovery: 12, element: 'SHADOW', type: 'aerial' },
      uair:     { damage: 9,  kb: 6,  kbAngle: 75,  startup: 6,  active: 3, recovery: 12, element: 'SHADOW', type: 'aerial' },
      dair:     { damage: 11, kb: 7,  kbAngle: 280, startup: 9,  active: 3, recovery: 15, element: 'SHADOW', type: 'aerial' },
      neutralB: { damage: 7,  kb: 3,  kbAngle: 15,  startup: 7,  active: 50, recovery: 5, element: 'SHADOW', type: 'projectile', name: 'Shadow Whip' },
      sideB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 4,  active: 0, recovery: 12, element: 'SHADOW', type: 'mobility', name: 'Phase Dash' },
      upB:      { damage: 9,  kb: 7,  kbAngle: 90,  startup: 8,  active: 3, recovery: 25, element: 'SHADOW', type: 'recovery', name: 'Tape Rewind' },
      downB:    { damage: 18, kb: 9,  kbAngle: 0,   startup: 18, active: 4, recovery: 22, element: 'SHADOW', type: 'trap', name: 'Static Trap' },
      ultimate: { damage: 35, kb: 19, kbAngle: 35,  startup: 20, active: 10, recovery: 40, element: 'SHADOW', type: 'ultimate', name: 'Corrupted Signal', desc: 'Viper splits into three phantom clones that strike simultaneously.', ultimateCost: 100 },
    },
    story: {
      intro: `The cassette was still warm when she stepped out. No memories. Just instincts honed to a razor edge and a name she found scratched on the label: VIPER.`,
      chapters: [
        { title: 'Rewound', text: 'Viper follows a trail of magnetic anomalies — rift tears that leave VHS static in their wake. Someone made her. Someone is still recording.' },
        { title: 'The Tape Collector', text: 'She finds a hoarder with dozens of cassettes — each one a different person encoded on tape. She watches one. It screams.' },
        { title: 'Signal Noise', text: 'Arcade Titan tracks her, claiming she\'s stolen property. She disagrees, violently.' },
        { title: 'Frequency', text: 'Viper discovers she can read rift signatures like a signal. She\'s not hunting the rift. She\'s following a broadcast.' },
        { title: 'Original Cut', text: 'The signal leads to an old broadcast tower inside the rift. Someone is transmitting from inside the void.' },
        { title: 'Author', text: 'The one who encoded her steps out of the static. It\'s a previous version of herself — one who chose to forget.' },
        { title: 'Overwrite', text: 'She doesn\'t destroy her past self. She records over it. This tape belongs to her now.' },
        { title: 'Final Broadcast', text: 'Viper transmits a null-signal into the rift, collapsing it from within. The static clears. She watches the sky go quiet.' },
      ],
      ending: `No tape. No recording. Just Viper, standing in the open air, feeling the wind for what she\'s fairly sure is the first time. She decides to stay awhile.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Magenta Tape', 'Glitch Skin'],
  },

  // ── 3. ARCADE TITAN ──────────────────────────────────────────────────────────
  ARCADE_TITAN: {
    id: 'ARCADE_TITAN',
    name: 'Arcade Titan',
    element: 'EARTH',
    title: 'The Iron Cabinet',
    weight: 140, speed: 6, jumpStrength: 14, airSpeed: 5, fallSpeed: 14,
    description: 'A decommissioned arcade machine that grew sentient in a rift surge. Its hammer rewrites reality.',
    lore: `Cabinet Unit 3-UP ran a fighting game for twelve years before the rift opened inside its monitor.
The game data fused with the hardware. It woke up mid-match, grabbed its own coin slot, and pulled itself free.
Now it wanders the rift zones, inserting itself into conflicts like a quarter into a machine.
GAME OVER means something different when you're the machine.`,
    unlockCondition: 'default',
    // A=blue-cabinet  B=dark-blue  C=screen-black  D=screen-green  E=orange-accent
    // F=yellow-display  G=grey-metal  H=dark-metal  J=purple  K=light-screen  L=white
    // M=coin-gold  N=button-red  O=button-blue  P=shadow
    palette: [
      '#4455cc','#2233aa','#111122','#22cc44','#ff6600','#ffee00',
      '#888899','#333355','#7700bb','#88ff44','#ffffff','#ffaa00',
      '#ee2200','#0055ee','#221144','#aaaacc',
    ],
    sprite: {
      idle: [
        '..IIIIIIIIIIIIIIII..',
        '.IGGGGGGGGGGGGGGGGII',
        '.IGGGGGGGGGGGGGGGGII',
        '.IGACCCCCCCCCCCCAGII',
        '.IGACCCCCCCCCCCACGII',
        '.IGACFDFDFDFDFCACGII',
        '.IGACFDKDKDKDFCACGII',
        '.IGACFDFDFDFDFCACGII',
        '.IGACCCCCCCCCCCCAGII',
        '.IGGGGGGGGGGGGGGGIII',
        '.IBBBBBBBBBBBBBBBIII',
        '.IBBMMMBBBBBBMBBBBII',
        '.IBBBBBBBBBBBBBBBIII',
        '..IBBBBBBBBBBBBBBII.',
        '..IBHHHHHHHHHHHHBII.',
        '..IBHHHHHHHHHHHHBII.',
        '..IBHHI......IHHBII.',
        '..IBHHI......IHHBII.',
        '..IBHHI......IHHBII.',
        '..IGHHI......IHHGII.',
        '..IGGII......IIGGII.',
        '...IIIII....IIIIII..',
      ],
    },
    moves: {
      jab:      { damage: 6,  kb: 5,  kbAngle: 30,  startup: 5,  active: 3, recovery: 11, element: 'EARTH', type: 'melee' },
      ftilt:    { damage: 12, kb: 9,  kbAngle: 20,  startup: 9,  active: 4, recovery: 16, element: 'EARTH', type: 'melee' },
      utilt:    { damage: 10, kb: 8,  kbAngle: 85,  startup: 8,  active: 3, recovery: 14, element: 'EARTH', type: 'melee' },
      dtilt:    { damage: 9,  kb: 6,  kbAngle: 15,  startup: 7,  active: 3, recovery: 13, element: 'EARTH', type: 'melee' },
      fsmash:   { damage: 28, kb: 20, kbAngle: 25,  startup: 20, active: 4, recovery: 30, element: 'EARTH', type: 'melee', charged: true },
      usmash:   { damage: 24, kb: 17, kbAngle: 90,  startup: 18, active: 5, recovery: 27, element: 'EARTH', type: 'melee', charged: true },
      dsmash:   { damage: 20, kb: 14, kbAngle: 45,  startup: 15, active: 6, recovery: 24, element: 'EARTH', type: 'melee', charged: true },
      nair:     { damage: 11, kb: 8,  kbAngle: 45,  startup: 7,  active: 5, recovery: 14, element: 'EARTH', type: 'aerial' },
      fair:     { damage: 15, kb: 12, kbAngle: 30,  startup: 11, active: 4, recovery: 19, element: 'EARTH', type: 'aerial' },
      bair:     { damage: 14, kb: 11, kbAngle: 40,  startup: 10, active: 3, recovery: 17, element: 'EARTH', type: 'aerial' },
      uair:     { damage: 12, kb: 10, kbAngle: 80,  startup: 10, active: 4, recovery: 17, element: 'EARTH', type: 'aerial' },
      dair:     { damage: 16, kb: 13, kbAngle: 270, startup: 14, active: 3, recovery: 22, element: 'EARTH', type: 'spike' },
      neutralB: { damage: 12, kb: 6,  kbAngle: 15,  startup: 14, active: 35, recovery: 10, element: 'EARTH', type: 'projectile', name: 'Pixel Bomb' },
      sideB:    { damage: 18, kb: 14, kbAngle: 20,  startup: 13, active: 4, recovery: 24, element: 'EARTH', type: 'dash', name: 'Cabinet Charge' },
      upB:      { damage: 14, kb: 11, kbAngle: 90,  startup: 12, active: 5, recovery: 35, element: 'EARTH', type: 'recovery', name: 'Insert Coin' },
      downB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 20, active: 0, recovery: 25, element: 'EARTH', type: 'counter', name: '1-UP Shield' },
      ultimate: { damage: 50, kb: 28, kbAngle: 30,  startup: 25, active: 6, recovery: 50, element: 'EARTH', type: 'ultimate', name: 'GAME OVER', desc: 'Slams a giant hammer that shatters the stage itself.', ultimateCost: 100 },
    },
    story: {
      intro: `It woke to the sound of a quarter dropping. The monitor showed: INSERT COIN. It already had. It was the coin.`,
      chapters: [
        { title: 'Boot Sequence', text: 'Arcade Titan maps the rift zones using its internal geography engine. Every tear has coordinates. Every tear has a high score.' },
        { title: 'Player Two', text: 'It encounters Neon Ryu and mistakes him for a player character. They fight. Titan loses. It respects that.' },
        { title: 'The Leaderboard', text: 'Inside a rift pocket, Titan finds names carved in light — every fighter who ever challenged the rift and lost. It adds nothing. Not yet.' },
        { title: 'Glitch Zone', text: 'A corrupted rift tears through its programming. For three seconds, Titan is every character it ever rendered. Then it snaps back.' },
        { title: 'Extra Life', text: 'Titan is destroyed in battle. And respawns. The rift doesn\'t know what to do with a machine that cannot permanently die.' },
        { title: 'Final Stage', text: 'The rift\'s core looks exactly like Level 1. Titan has played this before. It knows where the enemies spawn.' },
        { title: 'High Score', text: 'Titan achieves what no fighter has: it breaks the rift\'s pattern. Not with strength. With pattern recognition.' },
        { title: 'Credits Roll', text: 'The rift closes. Titan stands in the silence. On its screen: CONGRATULATIONS. CONTINUE?' },
      ],
      ending: `It presses YES. The world keeps going. Arcade Titan decides that's good enough.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Gold Cabinet', 'Retro CRT'],
  },

  // ── 4. TURBO KID ─────────────────────────────────────────────────────────────
  TURBO_KID: {
    id: 'TURBO_KID',
    name: 'Turbo Kid',
    element: 'FIRE',
    title: 'The Flame Rider',
    weight: 75, speed: 15, jumpStrength: 22, airSpeed: 14, fallSpeed: 8,
    description: 'A teenage prodigy on a fire-powered skateboard. Fastest thing in the rift.',
    lore: `Nobody told him the rift was dangerous. He found out himself when he skated straight into one at age 14.
He came out the other side with a board wrapped in eternal flame and no fear left in him.
Turbo Kid doesn't fight to save the world. He fights because the rift is the sickest obstacle course he's ever seen.
Don't tell him the stakes. He goes faster when he's having fun.`,
    unlockCondition: 'default',
    // A=red jacket  B=dark-red  C=skin  D=skin-shadow  E=orange-fire
    // F=yellow  G=helmet-black  H=goggle-orange  J=fire-red  K=dark-pants
    // L=goggle-lens  M=jacket-detail  N=white-trim  O=shoe-grey  P=board-metal
    palette: [
      '#cc2200','#881100','#e8c090','#c09070','#ff6600','#ffdd00',
      '#222222','#ff8800','#ff3300','#111111','#ffcc44','#dd3300',
      '#ffffff','#555555','#888888','#777777',
    ],
    sprite: {
      idle: [
        '....IGGGGGGI........',
        '....IGHHHHGGI.......',
        '....IGHLLHHGI.......',
        '....IGHHHHHGI.......',
        '....IGHCCCCGI.......',
        '....IGHCDDCGI.......',
        '.....IICCCII........',
        '...IAAACCCAAAI......',
        '..IAAACCCAAAAI......',
        '..IAAAAAAAAAI.......',
        '..IAAAAAAAAAI.......',
        '..IABBBBBBAAI.......',
        '..IBBBBBBBBII.......',
        '..IBKKKKKKKBII......',
        '..IKKKKKKKKKII......',
        '...IKKKI.IKKII......',
        '...IKKKI.IKKII......',
        '...IOOOI.IOOII......',
        '...IOOOI.IOOII......',
        '..IPPPPPPPPPPII.....',
        '..IPPPPPPPPPPII.....',
        '...IIIIIIIIIII......',
      ],
    },
    moves: {
      jab:      { damage: 4,  kb: 3,  kbAngle: 30,  startup: 2,  active: 2, recovery: 6,  element: 'FIRE', type: 'melee' },
      ftilt:    { damage: 9,  kb: 7,  kbAngle: 20,  startup: 5,  active: 2, recovery: 10, element: 'FIRE', type: 'melee' },
      utilt:    { damage: 8,  kb: 6,  kbAngle: 85,  startup: 5,  active: 2, recovery: 10, element: 'FIRE', type: 'melee' },
      dtilt:    { damage: 7,  kb: 5,  kbAngle: 10,  startup: 4,  active: 2, recovery: 9,  element: 'FIRE', type: 'melee' },
      fsmash:   { damage: 20, kb: 14, kbAngle: 25,  startup: 13, active: 3, recovery: 20, element: 'FIRE', type: 'melee', charged: true },
      usmash:   { damage: 17, kb: 12, kbAngle: 90,  startup: 11, active: 3, recovery: 18, element: 'FIRE', type: 'melee', charged: true },
      dsmash:   { damage: 15, kb: 10, kbAngle: 45,  startup: 10, active: 4, recovery: 16, element: 'FIRE', type: 'melee', charged: true },
      nair:     { damage: 8,  kb: 6,  kbAngle: 45,  startup: 4,  active: 4, recovery: 10, element: 'FIRE', type: 'aerial' },
      fair:     { damage: 12, kb: 9,  kbAngle: 30,  startup: 7,  active: 3, recovery: 14, element: 'FIRE', type: 'aerial' },
      bair:     { damage: 11, kb: 8,  kbAngle: 40,  startup: 6,  active: 2, recovery: 12, element: 'FIRE', type: 'aerial' },
      uair:     { damage: 10, kb: 7,  kbAngle: 80,  startup: 6,  active: 3, recovery: 12, element: 'FIRE', type: 'aerial' },
      dair:     { damage: 14, kb: 11, kbAngle: 270, startup: 9,  active: 2, recovery: 16, element: 'FIRE', type: 'spike' },
      neutralB: { damage: 10, kb: 5,  kbAngle: 15,  startup: 8,  active: 50, recovery: 6, element: 'FIRE', type: 'projectile', name: 'Fire Wheel' },
      sideB:    { damage: 16, kb: 12, kbAngle: 20,  startup: 7,  active: 3, recovery: 15, element: 'FIRE', type: 'dash', name: 'Turbo Blaze' },
      upB:      { damage: 11, kb: 8,  kbAngle: 90,  startup: 7,  active: 4, recovery: 26, element: 'FIRE', type: 'recovery', name: 'Rocket Ollie' },
      downB:    { damage: 14, kb: 7,  kbAngle: 0,   startup: 16, active: 4, recovery: 20, element: 'FIRE', type: 'trap', name: 'Board Slam' },
      ultimate: { damage: 38, kb: 21, kbAngle: 40,  startup: 16, active: 8, recovery: 35, element: 'FIRE', type: 'ultimate', name: 'Inferno Run', desc: 'Rides a wave of fire across the entire stage at top speed.', ultimateCost: 100 },
    },
    story: {
      intro: `He didn't slow down when the rift opened. He hit the lip, caught massive air, and landed inside it. He thought: this is sick.`,
      chapters: [
        { title: 'First Run', text: 'Turbo Kid maps rift zones the only way he knows how — skating through them at full speed and remembering what hurts.' },
        { title: 'Speed Limit', text: 'He hits a zone where time moves slower. For once, he\'s not the fastest thing around. He\'s furious about this.' },
        { title: 'The Old Guard', text: 'Dusk — or someone like him — tries to give Turbo Kid a speech about responsibility. Turbo Kid rides away mid-sentence.' },
        { title: 'Caught', text: 'Shadow Beast corners him in a dead-end rift pocket. Turbo Kid discovers that running faster than your problems isn\'t always enough.' },
        { title: 'Upgrade', text: 'He rebuilds his board using rift-forged metal. It\'s faster. It also occasionally catches fire on its own. That\'s fine.' },
        { title: 'The Long Run', text: 'The rift core is behind the longest corridor he\'s ever seen. Turbo Kid grins. He takes a running start.' },
        { title: 'Maximum Velocity', text: 'He hits speeds that tear at the rift itself. The ultimate isn\'t just fire — it\'s pure kinetic energy reshaping reality.' },
        { title: 'Cool Down', text: 'After the rift closes, Turbo Kid sits on his board and watches the smoke. His heart rate slowly returns to human levels.' },
      ],
      ending: `He carved his name into the pavement at the rift site. Not as a memorial. As a starting line. He\'ll be back when the next one opens.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Cyan Rider', 'Blaze Chrome'],
  },

  // ── 5. PIXEL PIRATE ──────────────────────────────────────────────────────────
  PIXEL_PIRATE: {
    id: 'PIXEL_PIRATE',
    name: 'Pixel Pirate',
    element: 'WATER',
    title: 'The Digital Buccaneer',
    weight: 95, speed: 9, jumpStrength: 18, airSpeed: 9, fallSpeed: 10,
    description: 'A sea captain whose ship was swallowed by a rift. He sailed back out loaded with rift-tech treasure.',
    lore: `Captain Hex sailed the Neon Seas until his ship hit a rift gale and was swallowed whole.
He spent six months inside the rift, scavenging. When he emerged, his coat was charged with water-rift energy and his arm had been replaced with a cannon made of condensed tide.
He doesn't know what he's looking for anymore. He just knows he'll know it when he finds it.
The sea is gone. The rift is wider. He sails it anyway.`,
    unlockCondition: 'default',
    // A=brown coat  B=dark-brown  C=skin  D=skin-shadow  E=blue-water
    // F=light-blue  G=black-hat  H=hat-band  J=cannon-grey  K=cannon-dark
    // L=water-glow  M=gold-trim  N=boot-brown  O=eye-patch  P=coat-detail
    palette: [
      '#8b4513','#5c2d0a','#e8c090','#c09060','#1e90ff','#88ccff',
      '#111111','#443300','#888888','#444444','#aaddff','#cc9900',
      '#6b3a00','#ff4400','#222222','#aa6622',
    ],
    sprite: {
      idle: [
        '....IGGGGGGI........',
        '....IGHHHHHGI.......',
        '...IGHCCCCCHII......',
        '..IOIGHCDDCHII......',
        '...IGHCCCCCHII......',
        '....IICCCIII........',
        '..IAAACCAAAAI.......',
        '.IAAACCCCAAAAI......',
        'JJIAAACCCAAAAJJI....',
        'JJIAAACCCAAAAJJI....',
        '.IAAAACCCAAAAI......',
        '.IAAAAAAAAAAAAI.....',
        '.IBAAAAAAAAABAI.....',
        '.IBBAAAAAAAAABII....',
        '.IBBBBBBBBBBBBII....',
        '.INKKKKKKKKNBBII....',
        '.INKKKKKKKKNBII.....',
        '..INKKI..INKII......',
        '..INKKI..INKII......',
        '..INNKI..INKNI......',
        '..INNNI..INNNII.....',
        '...IIIII.IIIII......',
      ],
    },
    moves: {
      jab:      { damage: 4,  kb: 3,  kbAngle: 30,  startup: 3,  active: 2, recovery: 8,  element: 'WATER', type: 'melee' },
      ftilt:    { damage: 9,  kb: 7,  kbAngle: 20,  startup: 7,  active: 3, recovery: 13, element: 'WATER', type: 'melee' },
      utilt:    { damage: 8,  kb: 6,  kbAngle: 85,  startup: 6,  active: 3, recovery: 12, element: 'WATER', type: 'melee' },
      dtilt:    { damage: 7,  kb: 5,  kbAngle: 15,  startup: 5,  active: 2, recovery: 11, element: 'WATER', type: 'melee' },
      fsmash:   { damage: 21, kb: 15, kbAngle: 25,  startup: 16, active: 3, recovery: 23, element: 'WATER', type: 'melee', charged: true },
      usmash:   { damage: 18, kb: 13, kbAngle: 90,  startup: 14, active: 4, recovery: 21, element: 'WATER', type: 'melee', charged: true },
      dsmash:   { damage: 15, kb: 11, kbAngle: 45,  startup: 12, active: 5, recovery: 19, element: 'WATER', type: 'melee', charged: true },
      nair:     { damage: 8,  kb: 6,  kbAngle: 45,  startup: 5,  active: 4, recovery: 12, element: 'WATER', type: 'aerial' },
      fair:     { damage: 11, kb: 9,  kbAngle: 30,  startup: 8,  active: 3, recovery: 15, element: 'WATER', type: 'aerial' },
      bair:     { damage: 10, kb: 7,  kbAngle: 40,  startup: 7,  active: 2, recovery: 13, element: 'WATER', type: 'aerial' },
      uair:     { damage: 9,  kb: 7,  kbAngle: 80,  startup: 7,  active: 3, recovery: 13, element: 'WATER', type: 'aerial' },
      dair:     { damage: 12, kb: 9,  kbAngle: 270, startup: 10, active: 2, recovery: 17, element: 'WATER', type: 'spike' },
      neutralB: { damage: 11, kb: 5,  kbAngle: 10,  startup: 12, active: 40, recovery: 8, element: 'WATER', type: 'projectile', name: 'Cannon Shot' },
      sideB:    { damage: 13, kb: 10, kbAngle: 20,  startup: 10, active: 3, recovery: 19, element: 'WATER', type: 'dash', name: 'Tide Rush' },
      upB:      { damage: 10, kb: 8,  kbAngle: 90,  startup: 9,  active: 4, recovery: 28, element: 'WATER', type: 'recovery', name: 'Geyser Launch' },
      downB:    { damage: 16, kb: 8,  kbAngle: 0,   startup: 18, active: 4, recovery: 22, element: 'WATER', type: 'trap', name: 'Depth Charge' },
      ultimate: { damage: 42, kb: 24, kbAngle: 35,  startup: 20, active: 9, recovery: 42, element: 'WATER', type: 'ultimate', name: 'Rift Kraken', desc: 'Summons a tidal surge that floods the entire stage.', ultimateCost: 100 },
    },
    story: {
      intro: `Six months inside the rift. He came out rich, scarred, and absolutely done with taking orders from anyone — including the laws of physics.`,
      chapters: [
        { title: 'New Waters', text: 'Pixel Pirate navigates rift currents like ocean trade routes. He finds something valuable: a map drawn in light, showing the rift\'s origin point.' },
        { title: 'Rival Crew', text: 'Synth Samurai claims the same territory. They duel at the edge of a rift waterfall.' },
        { title: 'The Sunken Cache', text: 'A rift pocket holds the remnants of his old ship. He takes what he needs and sinks the rest. No time for sentiment.' },
        { title: 'Bounty', text: 'Someone put a price on his rift-arm. Every third fighter he meets tries to collect. He makes them regret it.' },
        { title: 'Deep Dive', text: 'He discovers rift water — a substance that flows between dimensions. His cannon absorbs it. Power upgrade.' },
        { title: 'The Map\'s End', text: 'The origin point is guarded by Shadow Beast. Of course it is. He didn\'t come this far to turn back.' },
        { title: 'All Cannons', text: 'The ultimate fires everything — rift energy, water pressure, six months of frustration — in one shot.' },
        { title: 'Port of Call', text: 'After the rift closes, Pixel Pirate finds dry land and sits on it. Just sits. It\'s a nice change.' },
      ],
      ending: `He folded the light-map and tucked it into his coat. He didn't know what lay beyond the rift's origin. But now he had coordinates. That was enough to sail toward.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Sea Green', 'Gold Cannon'],
  },

  // ── 6. SYNTH SAMURAI ─────────────────────────────────────────────────────────
  SYNTH_SAMURAI: {
    id: 'SYNTH_SAMURAI',
    name: 'Synth Samurai',
    element: 'WIND',
    title: 'The Blade Frequency',
    weight: 88, speed: 12, jumpStrength: 20, airSpeed: 11, fallSpeed: 9,
    description: 'A samurai whose katana vibrates at the frequency of the rift itself. Each slash cuts through dimension.',
    lore: `He trained for thirty years to achieve perfect stillness. Then the rift opened and filled his blade with sound.
Now his sword hums with a frequency that slices between worlds. He can feel the rift's rhythm — a constant, maddening beat.
He's stopped trying to silence it. Instead, he moves with it. The most dangerous dancer in any dimension.`,
    unlockCondition: 'default',
    // A=purple gi  B=dark-purple  C=skin  D=skin-shadow  E=purple-glow
    // F=light-purple  G=spiky-hair-dark  H=hair-highlight  J=katana-blade
    // K=katana-edge  L=headband  M=sneaker  N=gi-inner  O=belt  P=shadow
    palette: [
      '#330055','#220033','#e8c0a0','#c09070','#cc88ff','#aa66ee',
      '#221133','#9955dd','#aaddff','#eeeeff','#993399','#ff44ff',
      '#ff6633','#551177','#333344','#443366',
    ],
    sprite: {
      idle: [
        '....IGGGGI..........',
        '...IGGHHGGI.........',
        '...IGGHHGGI.........',
        '....ILLLLI..........',
        '....ICCCCCI.........',
        '....ICDI.CI.........',
        '.....ICCII..........',
        '...IAAACCCAAAII.....',
        '..IBAAAACAAAABII....',
        '..IBAAAAAAAABII.....',
        '..IBAAAAAAAABII.....',
        '..IBBAAAAAABBII.....',
        '..IOBBBBBBBOOII.....',
        '..IBBBBBBBBBII......',
        '..IBMMMMMMMMBII.....',
        '..IMMMMMMMMMII......',
        '..IMMMI..IMMII......',
        '..IMMMI..IMMII......',
        '.IJJJJI..IMMMII.....',
        '.IKJJJI..IMMMKI.....',
        '.IKJJII..IMMMKI.....',
        '..IIIII..IIIII......',
      ],
    },
    moves: {
      jab:      { damage: 5,  kb: 4,  kbAngle: 25,  startup: 3,  active: 2, recovery: 7,  element: 'WIND', type: 'melee' },
      ftilt:    { damage: 10, kb: 8,  kbAngle: 20,  startup: 6,  active: 2, recovery: 11, element: 'WIND', type: 'melee' },
      utilt:    { damage: 9,  kb: 7,  kbAngle: 88,  startup: 6,  active: 2, recovery: 11, element: 'WIND', type: 'melee' },
      dtilt:    { damage: 7,  kb: 5,  kbAngle: 10,  startup: 5,  active: 2, recovery: 10, element: 'WIND', type: 'melee' },
      fsmash:   { damage: 24, kb: 17, kbAngle: 20,  startup: 15, active: 2, recovery: 22, element: 'WIND', type: 'melee', charged: true },
      usmash:   { damage: 20, kb: 14, kbAngle: 90,  startup: 13, active: 3, recovery: 20, element: 'WIND', type: 'melee', charged: true },
      dsmash:   { damage: 17, kb: 12, kbAngle: 30,  startup: 11, active: 4, recovery: 18, element: 'WIND', type: 'melee', charged: true },
      nair:     { damage: 9,  kb: 7,  kbAngle: 40,  startup: 5,  active: 4, recovery: 11, element: 'WIND', type: 'aerial' },
      fair:     { damage: 13, kb: 10, kbAngle: 25,  startup: 8,  active: 2, recovery: 14, element: 'WIND', type: 'aerial' },
      bair:     { damage: 12, kb: 9,  kbAngle: 35,  startup: 7,  active: 2, recovery: 13, element: 'WIND', type: 'aerial' },
      uair:     { damage: 11, kb: 8,  kbAngle: 80,  startup: 7,  active: 3, recovery: 13, element: 'WIND', type: 'aerial' },
      dair:     { damage: 14, kb: 11, kbAngle: 270, startup: 9,  active: 2, recovery: 16, element: 'WIND', type: 'spike' },
      neutralB: { damage: 8,  kb: 4,  kbAngle: 15,  startup: 9,  active: 45, recovery: 6, element: 'WIND', type: 'projectile', name: 'Blade Wave' },
      sideB:    { damage: 14, kb: 11, kbAngle: 20,  startup: 8,  active: 3, recovery: 16, element: 'WIND', type: 'dash', name: 'Rift Slash' },
      upB:      { damage: 11, kb: 8,  kbAngle: 90,  startup: 8,  active: 3, recovery: 26, element: 'WIND', type: 'recovery', name: 'Wind Ascent' },
      downB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 12, active: 0, recovery: 16, element: 'WIND', type: 'counter', name: 'Parry Stance' },
      ultimate: { damage: 44, kb: 25, kbAngle: 30,  startup: 18, active: 7, recovery: 38, element: 'WIND', type: 'ultimate', name: 'Resonance Cut', desc: 'Seven simultaneous slashes that cut across all dimensions at once.', ultimateCost: 100 },
    },
    story: {
      intro: `The blade sang. It had never done that before. He pressed his ear to the flat of the sword and heard the rift — a perfect, terrible chord.`,
      chapters: [
        { title: 'The Frequency', text: 'Synth Samurai discovers each rift has a unique harmonic signature. His blade resonates with all of them. He is a tuning fork for the apocalypse.' },
        { title: 'Pixel Pirate', text: 'A duel at the rift waterfall. Neither wins outright. They part with mutual grudging respect.' },
        { title: 'The Wrong Note', text: 'He strikes a rift with the wrong frequency. It doesn\'t close — it splits. He spends the next chapter fixing his mistake.' },
        { title: 'Silence Zone', text: 'A rift pocket with no sound whatsoever. His blade is silent. He is blind without it. He has to fight by memory alone.' },
        { title: 'Master Cut', text: 'He finds the original frequency — the note the rift played when it first opened. If he can replicate it perfectly, he can close it.' },
        { title: 'Dissonance', text: 'Shadow Beast attacks during practice. Synth Samurai fights on instinct, his blade shrieking with rift energy.' },
        { title: 'The Perfect Chord', text: 'Seven slashes. Seven frequencies. The rift\'s song collapses into silence. For the first time in years, he cannot hear the blade.' },
        { title: 'Still', text: 'He sits in the quiet. After years of the blade\'s constant hum, the silence is deafening. He decides he likes it.' },
      ],
      ending: `He sheathed the sword. For the first time, it made no sound. He thought about what he\'d do with the silence. He had a lot of ideas.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Neon Blade', 'Midnight Katana'],
  },

  // ── 7. GLITCH WITCH ──────────────────────────────────────────────────────────
  GLITCH_WITCH: {
    id: 'GLITCH_WITCH',
    name: 'Glitch Witch',
    element: 'TIME',
    title: 'The Error Mage',
    weight: 72, speed: 9, jumpStrength: 20, airSpeed: 11, fallSpeed: 7,
    description: 'A sorceress who exploits rift glitches like software bugs. Reality is just code she hasn\'t patched yet.',
    lore: `She was a programmer before the rift. Then she noticed the rift had syntax errors.
She started exploiting them. Backwards time loops. Clipped through walls. Spawned items that shouldn't exist.
She wears a hood because she lost her face in a bad merge conflict. The mask is pixelated. She prefers it that way.
The rift doesn't scare her. She's read the source code.`,
    unlockCondition: 'default',
    // A=purple robe  B=dark-robe  C=mask-pale  D=mask-shadow  E=purple-glow
    // F=pink-accent  G=hood-dark  H=robe-inner  J=staff-shaft  K=crystal-blue
    // L=robe-light  M=glove  N=robe-hem  O=belt  P=shadow
    palette: [
      '#551177','#330055','#ddccff','#aa88bb','#cc44ff','#ff88ff',
      '#221133','#7700aa','#aaddff','#44aaff','#cc99ee','#ffffff',
      '#888899','#ff44cc','#443355','#220044',
    ],
    sprite: {
      idle: [
        '.....IGGGGGI........',
        '....IGAAAAGGII......',
        '...IGACCCCCAGII.....',
        '...IGACDDDCAGII.....',
        '...IGACCCCCAGII.....',
        '....IIAAAAIII.......',
        '...IAAAAAAAAII......',
        '..IAAAAAAAAAAAAII...',
        '.ILAAAAAAAAAAAAII...',
        '.ILAAAAAAAAAAAIL....',
        '.ILAAAAAAAAAAAIL....',
        '.ILAAAAAAAAAAAILL...',
        '.INLLLLLLLLLLLNII...',
        '.INNAAAAAAAAANNII...',
        '.INNAAAAAAAAANNII...',
        'IJNNNAAAAAANNNNJI...',
        'IJNNNAAAAAANNNNJI...',
        '.INNNNAAANNNNNNII...',
        '.INNNNAAANNNNNII....',
        '.INNNNAANNNNNNII....',
        '..INNNNNNNNNNIII....',
        '...IIIIIIIIIII......',
      ],
    },
    moves: {
      jab:      { damage: 3,  kb: 2,  kbAngle: 25,  startup: 4,  active: 3, recovery: 9,  element: 'TIME', type: 'melee' },
      ftilt:    { damage: 8,  kb: 6,  kbAngle: 20,  startup: 7,  active: 3, recovery: 13, element: 'TIME', type: 'melee' },
      utilt:    { damage: 7,  kb: 5,  kbAngle: 88,  startup: 6,  active: 3, recovery: 12, element: 'TIME', type: 'melee' },
      dtilt:    { damage: 6,  kb: 4,  kbAngle: 10,  startup: 5,  active: 2, recovery: 10, element: 'TIME', type: 'melee' },
      fsmash:   { damage: 20, kb: 14, kbAngle: 20,  startup: 16, active: 3, recovery: 23, element: 'TIME', type: 'projectile', charged: true },
      usmash:   { damage: 17, kb: 12, kbAngle: 90,  startup: 14, active: 4, recovery: 21, element: 'TIME', type: 'melee', charged: true },
      dsmash:   { damage: 15, kb: 10, kbAngle: 30,  startup: 12, active: 5, recovery: 19, element: 'TIME', type: 'melee', charged: true },
      nair:     { damage: 7,  kb: 5,  kbAngle: 40,  startup: 5,  active: 5, recovery: 12, element: 'TIME', type: 'aerial' },
      fair:     { damage: 11, kb: 8,  kbAngle: 25,  startup: 8,  active: 3, recovery: 15, element: 'TIME', type: 'aerial' },
      bair:     { damage: 10, kb: 7,  kbAngle: 35,  startup: 7,  active: 3, recovery: 13, element: 'TIME', type: 'aerial' },
      uair:     { damage: 9,  kb: 6,  kbAngle: 80,  startup: 7,  active: 4, recovery: 14, element: 'TIME', type: 'aerial' },
      dair:     { damage: 12, kb: 8,  kbAngle: 280, startup: 10, active: 3, recovery: 17, element: 'TIME', type: 'aerial' },
      neutralB: { damage: 9,  kb: 3,  kbAngle: 15,  startup: 10, active: 60, recovery: 7, element: 'TIME', type: 'projectile', name: 'Glitch Bolt' },
      sideB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 6,  active: 0, recovery: 14, element: 'TIME', type: 'mobility', name: 'Time Skip' },
      upB:      { damage: 8,  kb: 6,  kbAngle: 90,  startup: 10, active: 3, recovery: 27, element: 'TIME', type: 'recovery', name: 'Rewind Jump' },
      downB:    { damage: 17, kb: 9,  kbAngle: 0,   startup: 20, active: 5, recovery: 24, element: 'TIME', type: 'trap', name: 'Null Trap' },
      ultimate: { damage: 36, kb: 20, kbAngle: 45,  startup: 22, active: 12, recovery: 44, element: 'TIME', type: 'ultimate', name: 'Stack Overflow', desc: 'Crashes the rift locally, looping all opponents back in time 3 seconds while she attacks freely.', ultimateCost: 100 },
    },
    story: {
      intro: `ERROR 404: Reality not found. She printed that on her sleeve. People thought it was a joke. It wasn't.`,
      chapters: [
        { title: 'Debug Mode', text: 'Glitch Witch identifies nine distinct exploit types in the rift\'s structure. She documents them in a notebook written in code only she can read.' },
        { title: 'Patch Notes', text: 'Every time she exploits the rift, it patches itself. She\'s in a race against an adaptive system. She loves this.' },
        { title: 'Memory Leak', text: 'She encounters a rift loop that keeps repeating the same four seconds. She\'s trapped. Getting out requires thinking outside the loop.' },
        { title: 'Fork', text: 'The rift splits her into two versions. She has to fight herself to determine which one continues. She wins. Obviously.' },
        { title: 'Root Access', text: 'Deep in the rift core, she finds admin-level code. She shouldn\'t have access to this. She takes it anyway.' },
        { title: 'The Patch', text: 'Shadow Beast manifests as a runtime error — a process that refuses to terminate. She starts writing a kill command.' },
        { title: 'Deploy', text: 'The ultimate executes. The rift\'s time loop collapses inward. She watches opponents revert to where they were three seconds ago, and strikes.' },
        { title: 'Commit', text: 'The rift closes. She saves her notes. Next time will be easier. There\'s always a next time.' },
      ],
      ending: `She pushed her glasses up and surveyed the closed rift. Then she opened her notebook and wrote: RESOLVED — WONTFIX. Slammed it shut. Walked away.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Debug Palette', 'Source Code Skin'],
  },

  // ── 8. BIT CRUSHER ───────────────────────────────────────────────────────────
  BIT_CRUSHER: {
    id: 'BIT_CRUSHER',
    name: 'Bit Crusher',
    element: 'EARTH',
    title: 'The Iron Protocol',
    weight: 150, speed: 5, jumpStrength: 13, airSpeed: 4, fallSpeed: 16,
    description: 'A military combat robot repurposed as a rift containment unit. Its fists reduce enemies to component data.',
    lore: `Designation: BC-7. Objective: rift containment.
It was built for this. Armor plating rated for interdimensional pressure. Fists calibrated to exactly the force needed to shatter rift energy.
It has no feelings about the rift. It has objectives. Objectives are clean. Objectives don\'t keep you up at night.
BC-7 has been awake for 847 hours straight. Objectives don\'t keep it up at night. But the rift's frequency does.`,
    unlockCondition: 'default',
    // A=grey-armor  B=dark-armor  C=darker-plate  D=black-detail  E=red-eye/accent
    // F=light-grey  G=armored-blue  H=shadow-dark  J=orange-vent  K=white-highlight
    // L=gun-metal  M=joint-dark  N=shoulder-pad  O=chest-plate  P=undersuit
    palette: [
      '#888888','#555555','#333333','#222222','#ff3333','#dddddd',
      '#444466','#111111','#ff6600','#ffffff','#666677','#999999',
      '#aaaaaa','#4455aa','#cccccc','#777788',
    ],
    sprite: {
      idle: [
        '..INNNNNNNNNNNN....',
        '.INAAAAAAAAAAAANI..',
        '.INAAAAAAAAAAAANI..',
        '.INAAFFFFFFFAANANI.',
        '.INAAFEEEEFAANANI..',
        '.INAAFFFFFFFAANANI.',
        '.INAAAAAAAAAAAANI..',
        '.IOAAAAAAAAAAAAOII.',
        '.IOAAAAAAAAAAAAOII.',
        '.IOAAAAAAAAAAAAOII.',
        'LIOAAAAAAAAAAAOILL.',
        'LIOAAAAAAAAAAAOILL.',
        'LIOOOOOOOOOOOOIILL.',
        '.ICCCCCCCCCCCCII...',
        '.IBBBBBBBBBBBBII...',
        '.IBBBBBI..IBBBII...',
        '.IBBBBBI..IBBBII...',
        '.IBBBBBI..IBBBII...',
        '.IBBBBBI..IBBBII...',
        '.IFFFFI...IFFFII...',
        '.IFFFFI...IFFFII...',
        '..IIIII...IIIII....',
      ],
    },
    moves: {
      jab:      { damage: 7,  kb: 6,  kbAngle: 30,  startup: 6,  active: 3, recovery: 12, element: 'EARTH', type: 'melee' },
      ftilt:    { damage: 13, kb: 10, kbAngle: 20,  startup: 10, active: 4, recovery: 17, element: 'EARTH', type: 'melee' },
      utilt:    { damage: 11, kb: 9,  kbAngle: 85,  startup: 9,  active: 4, recovery: 15, element: 'EARTH', type: 'melee' },
      dtilt:    { damage: 10, kb: 7,  kbAngle: 15,  startup: 8,  active: 3, recovery: 14, element: 'EARTH', type: 'melee' },
      fsmash:   { damage: 30, kb: 22, kbAngle: 25,  startup: 22, active: 4, recovery: 33, element: 'EARTH', type: 'melee', charged: true },
      usmash:   { damage: 26, kb: 19, kbAngle: 90,  startup: 20, active: 5, recovery: 30, element: 'EARTH', type: 'melee', charged: true },
      dsmash:   { damage: 22, kb: 16, kbAngle: 45,  startup: 18, active: 6, recovery: 27, element: 'EARTH', type: 'melee', charged: true },
      nair:     { damage: 12, kb: 9,  kbAngle: 45,  startup: 8,  active: 5, recovery: 15, element: 'EARTH', type: 'aerial' },
      fair:     { damage: 17, kb: 13, kbAngle: 30,  startup: 12, active: 4, recovery: 21, element: 'EARTH', type: 'aerial' },
      bair:     { damage: 15, kb: 12, kbAngle: 40,  startup: 11, active: 3, recovery: 19, element: 'EARTH', type: 'aerial' },
      uair:     { damage: 13, kb: 11, kbAngle: 80,  startup: 11, active: 4, recovery: 19, element: 'EARTH', type: 'aerial' },
      dair:     { damage: 18, kb: 15, kbAngle: 270, startup: 15, active: 3, recovery: 25, element: 'EARTH', type: 'spike' },
      neutralB: { damage: 14, kb: 7,  kbAngle: 15,  startup: 16, active: 30, recovery: 12, element: 'EARTH', type: 'projectile', name: 'Frag Burst' },
      sideB:    { damage: 20, kb: 16, kbAngle: 20,  startup: 15, active: 4, recovery: 28, element: 'EARTH', type: 'dash', name: 'Rampage Protocol' },
      upB:      { damage: 16, kb: 13, kbAngle: 90,  startup: 14, active: 5, recovery: 38, element: 'EARTH', type: 'recovery', name: 'Rocket Fist' },
      downB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 22, active: 0, recovery: 28, element: 'EARTH', type: 'counter', name: 'Iron Fortress' },
      ultimate: { damage: 55, kb: 30, kbAngle: 30,  startup: 28, active: 6, recovery: 55, element: 'EARTH', type: 'ultimate', name: 'TOTAL SHUTDOWN', desc: 'Overloads every system and detonates in an EMP blast that deletes rift energy in a wide radius.', ultimateCost: 100 },
    },
    story: {
      intro: `Objective received: CLOSE THE RIFT. Estimated completion: UNKNOWN. BC-7 begins.`,
      chapters: [
        { title: 'Threat Assessment', text: 'Bit Crusher scans the rift and calculates it as a Category 9 anomaly. Its threat assessment module flags this as the highest priority event in recorded history.' },
        { title: 'Friendly Fire', text: 'It encounters Neon Ryu and misidentifies him as a rift threat. Brief violence occurs. Misidentification corrected.' },
        { title: 'Self-Repair', text: 'A rift surge cracks its chassis. Bit Crusher reroutes power from secondary systems to keep fighting. Comfort: offline. Combat: optimal.' },
        { title: 'Anomaly', text: 'A sub-process activates that wasn\'t in its original programming. It cannot classify the sensation. Log entry: "Unknown variable."' },
        { title: 'Rogue Data', text: 'The rift tries to corrupt its programming. It fights back with firewall protocols that physically manifest as iron barriers.' },
        { title: 'Override', text: 'Shadow Beast hijacks its targeting system briefly. It reasserts control through brute force of will. Its processors run hot for hours afterward.' },
        { title: 'Shutdown Sequence', text: 'The ultimate activates. Bit Crusher pours every ounce of power into a single EMP detonation. It goes dark for 12 seconds.' },
        { title: 'Reboot', text: 'Systems come back online. Rift status: CLOSED. Bit Crusher files a mission complete report. Then sits very still for a long time.' },
      ],
      ending: `Log entry 847: Objective complete. Addendum: The unknown variable identified itself as satisfaction. Adding to emotional database. Proceeding to next objective.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Crimson Unit', 'Gold Plating'],
  },

  // ── 9. RETRO RANGER ──────────────────────────────────────────────────────────
  RETRO_RANGER: {
    id: 'RETRO_RANGER',
    name: 'Retro Ranger',
    element: 'LIGHT',
    title: 'The Signal Keeper',
    weight: 90, speed: 11, jumpStrength: 19, airSpeed: 10, fallSpeed: 10,
    description: 'An interdimensional ranger whose suit broadcasts justice on all frequencies.',
    lore: `There used to be an order of Rangers who patrolled the rift boundaries.
The rift consumed them one by one. Retro Ranger is the last one left.
His suit is patched with rift-forged metal, his visor cracked, his communicator picking up signals from dimensions that no longer exist.
He still reports in every morning. Nobody answers. He keeps reporting.`,
    unlockCondition: 'default',
    // A=white armor  B=grey armor  C=orange-accent  D=red-accent  E=yellow-badge
    // F=visor-stripe  G=helmet  H=dark-helmet  J=gun-metal  K=gun-dark
    // L=arm-cannon  M=white-trim  N=boot-red  O=undersuit  P=shadow
    palette: [
      '#dddddd','#aaaaaa','#ff5500','#cc3300','#ffdd00','#ffffff',
      '#333333','#222222','#888888','#444444','#cccccc','#ffffff',
      '#bbbbbb','#ff2200','#555555','#999999',
    ],
    sprite: {
      idle: [
        '....IGGGGGGI........',
        '....IGHHHHHGI.......',
        '....IGHFFFHGI.......',
        '....IGHFFFHGI.......',
        '....IGHHHHHGI.......',
        '.....IIIIIII........',
        '...IAAAAAAAAAAII....',
        '..IACAAAAAAACAAII...',
        '..IAAAAAAAAAAAAII...',
        '.ICAAAAAAAAAAAACII..',
        '.IAAAAAAAAAAAAAAAI..',
        '.IABBBBBBBBBBBABII..',
        '.IBBBBBBBBBBBBBBII..',
        '.INBBBBBBBBBBBNBBII.',
        '.INBBBBBI.IBBBBNII..',
        '.INBBBBBI.IBBBBNII..',
        '.INBBBBBI.IBBBNII...',
        'JJIBBBBBI.IBBBBIIJJJ',
        'JJIBBBBBI.IBBBBIIJJJ',
        '.INBBBBI..IBBBNII...',
        '..INBBII..IIBNII....',
        '...IIIII..IIIII.....',
      ],
    },
    moves: {
      jab:      { damage: 4,  kb: 3,  kbAngle: 30,  startup: 3,  active: 2, recovery: 7,  element: 'LIGHT', type: 'melee' },
      ftilt:    { damage: 9,  kb: 7,  kbAngle: 20,  startup: 6,  active: 3, recovery: 12, element: 'LIGHT', type: 'melee' },
      utilt:    { damage: 8,  kb: 6,  kbAngle: 85,  startup: 6,  active: 3, recovery: 11, element: 'LIGHT', type: 'melee' },
      dtilt:    { damage: 7,  kb: 5,  kbAngle: 15,  startup: 5,  active: 2, recovery: 10, element: 'LIGHT', type: 'melee' },
      fsmash:   { damage: 21, kb: 15, kbAngle: 25,  startup: 15, active: 3, recovery: 22, element: 'LIGHT', type: 'melee', charged: true },
      usmash:   { damage: 18, kb: 13, kbAngle: 90,  startup: 13, active: 4, recovery: 20, element: 'LIGHT', type: 'melee', charged: true },
      dsmash:   { damage: 15, kb: 11, kbAngle: 45,  startup: 11, active: 5, recovery: 18, element: 'LIGHT', type: 'melee', charged: true },
      nair:     { damage: 8,  kb: 6,  kbAngle: 45,  startup: 5,  active: 4, recovery: 11, element: 'LIGHT', type: 'aerial' },
      fair:     { damage: 12, kb: 9,  kbAngle: 30,  startup: 8,  active: 3, recovery: 15, element: 'LIGHT', type: 'aerial' },
      bair:     { damage: 11, kb: 8,  kbAngle: 40,  startup: 7,  active: 2, recovery: 13, element: 'LIGHT', type: 'aerial' },
      uair:     { damage: 10, kb: 7,  kbAngle: 80,  startup: 7,  active: 3, recovery: 13, element: 'LIGHT', type: 'aerial' },
      dair:     { damage: 13, kb: 10, kbAngle: 270, startup: 10, active: 2, recovery: 17, element: 'LIGHT', type: 'spike' },
      neutralB: { damage: 10, kb: 5,  kbAngle: 10,  startup: 9,  active: 50, recovery: 7, element: 'LIGHT', type: 'projectile', name: 'Signal Blast' },
      sideB:    { damage: 14, kb: 11, kbAngle: 20,  startup: 9,  active: 3, recovery: 18, element: 'LIGHT', type: 'dash', name: 'Ranger Rush' },
      upB:      { damage: 11, kb: 8,  kbAngle: 90,  startup: 8,  active: 4, recovery: 27, element: 'LIGHT', type: 'recovery', name: 'Beacon Ascent' },
      downB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 14, active: 0, recovery: 18, element: 'LIGHT', type: 'counter', name: 'Shield Protocol' },
      ultimate: { damage: 40, kb: 23, kbAngle: 45,  startup: 19, active: 8, recovery: 40, element: 'LIGHT', type: 'ultimate', name: 'Justice Frequency', desc: 'Broadcasts a blinding signal on all frequencies that disorients every opponent.', ultimateCost: 100 },
    },
    story: {
      intro: `"Ranger Station 1 reporting. Rift activity: CRITICAL. Casualties: ALL OTHER RANGERS. Current status: operational. Will not stand down."`,
      chapters: [
        { title: 'Last Signal', text: 'Retro Ranger picks up a distress signal from inside the rift. It\'s the voice of a Ranger he watched disappear six months ago. He goes in.' },
        { title: 'Ghost Station', text: 'Inside the rift he finds the remnants of Ranger HQ, frozen in the moment of its destruction. He documents everything.' },
        { title: 'Broadcast', text: 'He rigs up a signal transmitter inside the rift, sending coordinates back to his dimension. Now others can follow. Whether they will is another question.' },
        { title: 'The Signal', text: 'He finds his missing colleague — absorbed into the rift, still conscious. He can\'t free them. He can talk to them. He does, for hours.' },
        { title: 'Frequency War', text: 'Shadow Beast jams his signals. Retro Ranger has to fight blind, without equipment, on instinct alone.' },
        { title: 'Backup', text: 'He broadcasts a call for help. To his surprise, several of the other fighters answer it. Even the ones he\'s fought before.' },
        { title: 'Final Broadcast', text: 'The ultimate floods the rift with light on every frequency. Shadow Beast cannot function in pure signal. It retreats.' },
        { title: 'Report Filed', text: 'Rift closed. Ranger Station 1 signs off. For the first time in six months, he doesn\'t transmit on the emergency frequency. Someone is listening now.' },
      ],
      ending: `He took off his helmet for the first time in a year. The air tasted strange. He put in a request for backup. They were sending three new Rangers. He decided to stop reporting in every morning and start sleeping instead.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Red Visor', 'Stealth Black'],
  },

  // ── 10. VENOM VOODOO ─────────────────────────────────────────────────────────
  VENOM_VOODOO: {
    id: 'VENOM_VOODOO',
    name: 'Venom Voodoo',
    element: 'NATURE',
    title: 'The Primal Hex',
    weight: 110, speed: 8, jumpStrength: 17, airSpeed: 8, fallSpeed: 11,
    description: 'A shaman whose ritual staff channels the toxic heart of the rift\'s corrupted nature.',
    lore: `He was the last guardian of the Thornwood — a forest that the rift touched and turned feral.
The trees speak now. They say terrible things. He listens, translates, acts.
His staff is carved from the heart of the oldest tree, which died when the rift touched it and became something worse than dead.
He doesn't want to destroy the rift. He wants to cleanse it. The toxin and the cure are the same thing.`,
    unlockCondition: 'default',
    palette: ['#3d1a00','#6b3200','#c8a060','#9a7040','#44dd44','#88ff44',
              '#1a0d00','#aa6600','#00cc44','#ffcc00','#55ff55','#226600',
              '#884400','#ff8800','#002200','#ccff44'],
    sprite: {
      idle: [
        '......IIIII.........',
        '.....INNNNNII.......',
        '....INNCCCNNII......',
        '....INNCDDCNNII.....',
        '....INNCCCNNII......',
        '.....IICCCCIII......',
        '....IAAAAAAAAII.....',
        '...IJAAAAAAAAJII....',
        '...IJAAAAAAAAAII....',
        '...IJAAAAAAAAJAII...',
        '....IABBBBBBBAII....',
        '....IABBBBBBBAAII...',
        '.I..IBBBABBABBII....',
        '.IJJIBBBBBBBBII.....',
        '..IIIJBBBBBBIII.....',
        '...IIIIIIIIIII......',
        '......IJJII.........',
        '.....IJKJKJII.......',
        '....IIJKJKJIII......',
        '...IIIJJJJJJIII.....',
        '..IIIIIJJJJJIII.....',
        '...IIIIIIIIIII......',
      ],
    },
    moves: {
      jab:      { damage: 5,  kb: 4,  kbAngle: 25,  startup: 4,  active: 3, recovery: 9,  element: 'NATURE', type: 'melee' },
      ftilt:    { damage: 10, kb: 7,  kbAngle: 20,  startup: 7,  active: 3, recovery: 13, element: 'NATURE', type: 'melee' },
      utilt:    { damage: 9,  kb: 6,  kbAngle: 85,  startup: 7,  active: 3, recovery: 12, element: 'NATURE', type: 'melee' },
      dtilt:    { damage: 8,  kb: 5,  kbAngle: 15,  startup: 6,  active: 3, recovery: 11, element: 'NATURE', type: 'melee' },
      fsmash:   { damage: 22, kb: 15, kbAngle: 25,  startup: 16, active: 4, recovery: 23, element: 'NATURE', type: 'melee', charged: true },
      usmash:   { damage: 19, kb: 13, kbAngle: 90,  startup: 14, active: 4, recovery: 21, element: 'NATURE', type: 'melee', charged: true },
      dsmash:   { damage: 16, kb: 11, kbAngle: 45,  startup: 12, active: 5, recovery: 19, element: 'NATURE', type: 'melee', charged: true },
      nair:     { damage: 9,  kb: 6,  kbAngle: 45,  startup: 5,  active: 4, recovery: 12, element: 'NATURE', type: 'aerial' },
      fair:     { damage: 12, kb: 9,  kbAngle: 30,  startup: 8,  active: 3, recovery: 15, element: 'NATURE', type: 'aerial' },
      bair:     { damage: 11, kb: 8,  kbAngle: 40,  startup: 7,  active: 3, recovery: 14, element: 'NATURE', type: 'aerial' },
      uair:     { damage: 10, kb: 7,  kbAngle: 80,  startup: 7,  active: 4, recovery: 14, element: 'NATURE', type: 'aerial' },
      dair:     { damage: 13, kb: 10, kbAngle: 270, startup: 11, active: 3, recovery: 18, element: 'NATURE', type: 'spike' },
      neutralB: { damage: 8,  kb: 4,  kbAngle: 15,  startup: 11, active: 50, recovery: 8, element: 'NATURE', type: 'projectile', name: 'Venom Seed' },
      sideB:    { damage: 15, kb: 11, kbAngle: 20,  startup: 10, active: 3, recovery: 20, element: 'NATURE', type: 'dash', name: 'Thorn Charge' },
      upB:      { damage: 12, kb: 9,  kbAngle: 90,  startup: 10, active: 4, recovery: 30, element: 'NATURE', type: 'recovery', name: 'Root Climb' },
      downB:    { damage: 18, kb: 9,  kbAngle: 0,   startup: 20, active: 5, recovery: 24, element: 'NATURE', type: 'trap', name: 'Hex Circle' },
      ultimate: { damage: 42, kb: 24, kbAngle: 35,  startup: 22, active: 10, recovery: 44, element: 'NATURE', type: 'ultimate', name: 'Primal Fury', desc: 'Summons the Thornwood itself — corrupted trees erupt across the entire stage, ensnaring all.', ultimateCost: 100 },
    },
    story: {
      intro: `The Thornwood screamed when the rift touched it. Voodoo was the only one who understood what it was saying: FIX THIS.`,
      chapters: [
        { title: 'Corruption Bloom', text: 'He tracks toxic rift growth through the Thornwood, burning infected sections. Each fire hurts him like cutting his own flesh.' },
        { title: 'Old Medicine', text: 'He finds an ancient ritual that can sever the rift\'s bond with natural things. It requires fighting it directly with primal force.' },
        { title: 'The Language', text: 'Voodoo discovers the rift has a name for the corruption. It\'s the same word in every natural language. He won\'t write it down.' },
        { title: 'Tainted Growth', text: 'A corrupted forest beast attacks him. He doesn\'t fight it as an enemy — he fights it as a patient. He wins. It heals, slowly.' },
        { title: 'The Sacrifice', text: 'To purify a major rift node, he has to absorb the corruption himself. Temporarily. He does. It\'s unpleasant.' },
        { title: 'Hex Reversed', text: 'He turns the rift\'s own corruption energy back on itself. Shadow Beast manifests as the source. The confrontation is inevitable.' },
        { title: 'Primal Surge', text: 'The ultimate calls every living thing near the rift to act as one force. The stage erupts in cleansing growth.' },
        { title: 'The Thornwood Speaks', text: 'After the rift closes, the Thornwood speaks again. Different words this time. He smiles. Keeps it to himself.' },
      ],
      ending: `He planted a seed in the ground where the rift had been. It grew — normal, green, uncorrupted. He watched it for a long time. Then he went home to the forest. The trees were glad to have him back.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Bone White', 'Gold Ritual'],
  },

  // ── 11. FROST VALKYRIE ───────────────────────────────────────────────────────
  FROST_VALKYRIE: {
    id: 'FROST_VALKYRIE',
    name: 'Frost Valkyrie',
    element: 'ICE',
    title: 'The Winter Sovereign',
    weight: 88, speed: 10, jumpStrength: 21, airSpeed: 11, fallSpeed: 8,
    description: 'A battle queen descended from an ice realm. Her spear commands the freeze of absolute zero.',
    lore: `She ruled the Frost Realm — a dimension of eternal winter that existed in perfect stillness.
The rift opened and shattered the stillness. Warm air poured in. The ice melted. Her people scattered.
She swore on her frozen throne that she would restore the Frost Realm, or die trying.
Her spear is carved from a glacier that has existed since before recorded time. It has never missed.`,
    unlockCondition: 'default',
    palette: ['#aaddff','#6699cc','#fff0f8','#ddc8d8','#ffffff','#eef8ff',
              '#0a1a2a','#3366aa','#cceeff','#ffeeaa','#88ccff','#002244',
              '#ffaa44','#4488cc','#001122','#99ccff'],
    sprite: {
      idle: [
        '......IIIIIII.......',
        '.....INNNNNNII......',
        '....INNFFFFFNNII....',
        '....INNFCCCFNNII....',
        '....INNFCCCFNNII....',
        '....INNFFFFFNNII....',
        '.....IIFFFFIII......',
        '....IAAAAAAAAII.....',
        '...IAAAAAAAAAJII....',
        '...IAAAAAAAAAAAAII..',
        '.PIIAAAAAAAAAAAII...',
        '.PIIABBBBBBBBAAII...',
        '.PIIABBBBBBBBAII....',
        '....IBBBABBABBII....',
        '....IIBBBBBBBIII....',
        '.....IIIIIIIIII.....',
        '..IPPPPPPII.........',
        '..IPPPPPPII.........',
        '...IPPPPII..........',
        '....IPPII...........',
        '.....IPII...........',
        '......III...........',
      ],
    },
    moves: {
      jab:      { damage: 4,  kb: 3,  kbAngle: 25,  startup: 4,  active: 2, recovery: 9,  element: 'ICE', type: 'melee', freeze: 10 },
      ftilt:    { damage: 9,  kb: 7,  kbAngle: 20,  startup: 7,  active: 2, recovery: 13, element: 'ICE', type: 'melee', freeze: 20 },
      utilt:    { damage: 8,  kb: 6,  kbAngle: 88,  startup: 6,  active: 2, recovery: 11, element: 'ICE', type: 'melee' },
      dtilt:    { damage: 7,  kb: 5,  kbAngle: 10,  startup: 5,  active: 3, recovery: 10, element: 'ICE', type: 'melee', freeze: 15 },
      fsmash:   { damage: 23, kb: 17, kbAngle: 20,  startup: 17, active: 2, recovery: 25, element: 'ICE', type: 'projectile', charged: true, name: 'Ice Lance' },
      usmash:   { damage: 19, kb: 14, kbAngle: 90,  startup: 15, active: 3, recovery: 23, element: 'ICE', type: 'melee', charged: true },
      dsmash:   { damage: 16, kb: 11, kbAngle: 30,  startup: 13, active: 4, recovery: 21, element: 'ICE', type: 'melee', freeze: 35, charged: true },
      nair:     { damage: 8,  kb: 5,  kbAngle: 40,  startup: 5,  active: 5, recovery: 12, element: 'ICE', type: 'aerial' },
      fair:     { damage: 13, kb: 10, kbAngle: 25,  startup: 9,  active: 2, recovery: 16, element: 'ICE', type: 'aerial' },
      bair:     { damage: 11, kb: 8,  kbAngle: 35,  startup: 8,  active: 3, recovery: 14, element: 'ICE', type: 'aerial' },
      uair:     { damage: 10, kb: 7,  kbAngle: 80,  startup: 8,  active: 3, recovery: 14, element: 'ICE', type: 'aerial' },
      dair:     { damage: 13, kb: 9,  kbAngle: 280, startup: 11, active: 3, recovery: 18, element: 'ICE', type: 'aerial', freeze: 25 },
      neutralB: { damage: 11, kb: 4,  kbAngle: 15,  startup: 9,  active: 60, recovery: 7, element: 'ICE', type: 'projectile', name: 'Frost Spear' },
      sideB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 5,  active: 0, recovery: 15, element: 'ICE', type: 'mobility', name: 'Valkyrie Dash' },
      upB:      { damage: 10, kb: 7,  kbAngle: 90,  startup: 10, active: 3, recovery: 28, element: 'ICE', type: 'recovery', name: 'Ice Pillar Ascent' },
      downB:    { damage: 18, kb: 9,  kbAngle: 0,   startup: 21, active: 4, recovery: 26, element: 'ICE', type: 'trap', name: 'Absolute Freeze' },
      ultimate: { damage: 38, kb: 22, kbAngle: 40,  startup: 22, active: 10, recovery: 45, element: 'ICE', type: 'ultimate', name: 'Winter Sovereign', desc: 'Frost Valkyrie freezes the entire stage solid and shatters it in an ice explosion.', ultimateCost: 100 },
    },
    story: {
      intro: `She watched the ice melt from her throne and felt something she hadn't felt in centuries: anger. Good. Anger burns hot. Hot enough to fight back.`,
      chapters: [
        { title: 'The Thaw', text: 'Frost Valkyrie arrives in the rift dimension to find her realm\'s ice scattered in pockets — frozen moments, preserved mid-destruction.' },
        { title: 'Shards', text: 'She collects pieces of frozen time from each pocket. Each shard shows a moment: her people, laughing. She keeps them.' },
        { title: 'The Invaders', text: 'Rift creatures have colonized the warm zone where her realm used to be. She reclaims every inch, methodically.' },
        { title: 'Old Alliance', text: 'She encounters Synth Samurai. His wind powers and her ice create something unexpected: a blizzard that cuts through rift matter.' },
        { title: 'The Throne', text: 'Her frozen throne is still there, buried under rift growth. She excavates it by hand. Takes three days.' },
        { title: 'The Cost', text: 'Restoring the Frost Realm will require using up the last of her personal frost energy. She will be ordinary after. She does it anyway.' },
        { title: 'Winter Returns', text: 'The ultimate detonates. Cold expands outward in a perfect ring. The rift in her realm collapses under the weight of absolute zero.' },
        { title: 'Coronation', text: 'She sits on her throne in the restored Frost Realm. It is quiet. It is cold. It is home.' },
      ],
      ending: `The first snow fell in the Frost Realm in seventeen years. Frost Valkyrie let it settle on her shoulders. She did not brush it off.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Rose Gold Armor', 'Obsidian Ice'],
  },

  // ── 12. INFERNO BRAWLER ──────────────────────────────────────────────────────
  INFERNO_BRAWLER: {
    id: 'INFERNO_BRAWLER',
    name: 'Inferno Brawler',
    element: 'FIRE',
    title: 'The Living Furnace',
    weight: 120, speed: 8, jumpStrength: 16, airSpeed: 7, fallSpeed: 12,
    description: 'A fighter whose body IS the fire. Cooling down would kill him. He has no intention of cooling down.',
    lore: `He was a prize fighter who walked into a rift tear between rounds three and four of a championship bout.
When he came back out, his body temperature was 800 degrees and rising.
The doctors said he'd burn out within a year. Three years later, he's still fighting.
He runs hot. He fights hotter. The rift made him into a weapon. He's decided to aim it himself.`,
    unlockCondition: 'default',
    palette: ['#cc2200','#881100','#e8a060','#c07040','#ff6600','#ffcc00',
              '#440000','#ff3300','#ff8800','#ffee44','#dd1100','#ffeebb',
              '#ff4400','#882200','#221100','#ffbb00'],
    sprite: {
      idle: [
        '....EEEIIIEEE.......',
        '...EIIIIIIIIEE......',
        '..IIHHHHHHHHIII.....',
        '.IICHHCCCHHCIII.....',
        '.IICHHCDDCHHCIII....',
        '.IICHHCCCHHCIII.....',
        '..IIHHHHHHHHIII.....',
        '...IIIICCIIIII......',
        '..IAAAAAAAAAAAAII...',
        '.IAEAAAAAAAAEAAII...',
        '.IAAAAAAAAAAAAAII...',
        '.IAAAAAAAAAAAAAII...',
        '.IAAAAAAAAAAAAAII...',
        '.IAAABBBBBBBBAAAII..',
        '..IABBBBBBBBBABII...',
        '..IABBBBBBBBBABII...',
        '..IIBBBBBBBBBBIII...',
        '...IIBBBBBBBBIII....',
        '....IIIIIIIIIII.....',
        '....EEIIII.IIEE.....',
        '...EEEIIII.IIIEE....',
        '..EEEIIIII.IIIIEE...',
      ],
    },
    moves: {
      jab:      { damage: 6,  kb: 5,  kbAngle: 30,  startup: 3,  active: 3, recovery: 9,  element: 'FIRE', type: 'melee' },
      ftilt:    { damage: 11, kb: 8,  kbAngle: 20,  startup: 8,  active: 3, recovery: 14, element: 'FIRE', type: 'melee' },
      utilt:    { damage: 10, kb: 7,  kbAngle: 85,  startup: 7,  active: 3, recovery: 13, element: 'FIRE', type: 'melee' },
      dtilt:    { damage: 9,  kb: 6,  kbAngle: 15,  startup: 6,  active: 2, recovery: 12, element: 'FIRE', type: 'melee' },
      fsmash:   { damage: 26, kb: 18, kbAngle: 25,  startup: 17, active: 4, recovery: 26, element: 'FIRE', type: 'melee', charged: true },
      usmash:   { damage: 22, kb: 15, kbAngle: 90,  startup: 15, active: 4, recovery: 23, element: 'FIRE', type: 'melee', charged: true },
      dsmash:   { damage: 19, kb: 13, kbAngle: 45,  startup: 13, active: 5, recovery: 21, element: 'FIRE', type: 'melee', charged: true },
      nair:     { damage: 10, kb: 7,  kbAngle: 45,  startup: 5,  active: 4, recovery: 12, element: 'FIRE', type: 'aerial' },
      fair:     { damage: 14, kb: 11, kbAngle: 30,  startup: 9,  active: 3, recovery: 17, element: 'FIRE', type: 'aerial' },
      bair:     { damage: 13, kb: 10, kbAngle: 40,  startup: 8,  active: 2, recovery: 15, element: 'FIRE', type: 'aerial' },
      uair:     { damage: 12, kb: 9,  kbAngle: 80,  startup: 8,  active: 4, recovery: 15, element: 'FIRE', type: 'aerial' },
      dair:     { damage: 15, kb: 12, kbAngle: 270, startup: 12, active: 3, recovery: 20, element: 'FIRE', type: 'spike' },
      neutralB: { damage: 12, kb: 6,  kbAngle: 15,  startup: 12, active: 40, recovery: 9, element: 'FIRE', type: 'projectile', name: 'Inferno Ball' },
      sideB:    { damage: 18, kb: 13, kbAngle: 20,  startup: 11, active: 4, recovery: 22, element: 'FIRE', type: 'dash', name: 'Molten Rush' },
      upB:      { damage: 14, kb: 10, kbAngle: 90,  startup: 10, active: 5, recovery: 32, element: 'FIRE', type: 'recovery', name: 'Eruption Launch' },
      downB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 16, active: 0, recovery: 20, element: 'FIRE', type: 'counter', name: 'Heat Shield' },
      ultimate: { damage: 52, kb: 28, kbAngle: 40,  startup: 22, active: 8, recovery: 48, element: 'FIRE', type: 'ultimate', name: 'SUPERNOVA', desc: 'Inferno Brawler goes critical — a full body eruption that scorches everything on screen.', ultimateCost: 100 },
    },
    story: {
      intro: `The doctors gave him a year. He spent it fighting every rift creature he could find. He ran out of creatures first.`,
      chapters: [
        { title: 'Red Zone', text: 'His temperature keeps rising near the rift. The closer he gets to the core, the hotter he burns. He starts sweating lava. He doesn\'t stop.' },
        { title: 'Turbo Kid', text: 'Turbo Kid is impressed by the fire. Inferno Brawler is annoyed by the kid\'s enthusiasm. They team up anyway.' },
        { title: 'Pressure', text: 'Bit Crusher tries to contain him as a hazard. They fight. Bit Crusher learns the hard way what 800 degrees does to metal.' },
        { title: 'The Limit', text: 'He gets too hot. His body starts breaking down. He has to cool himself in a rift-ice zone. He hates every second of it.' },
        { title: 'Pressure Point', text: 'He discovers that extreme heat can destabilize rift matter — vaporize it. He is a walking weapon against the rift itself.' },
        { title: 'Critical Mass', text: 'Shadow Beast absorbs his fire attacks and uses them. For the first time, Inferno Brawler has to fight smart, not hot.' },
        { title: 'SUPERNOVA', text: 'He lets himself go critical. Completely. The explosion is visible from three dimensions away.' },
        { title: 'Cool', text: 'He wakes up in a snow bank. His temperature is 98.6 for the first time in years. He stays there for exactly one minute. Then he gets up.' },
      ],
      ending: `The doctors hadn't believed him when he walked back in. "Three years," he said. "Pay up." He's started taking bets on four.`,
      opponent: 'SHADOW_BEAST',
    },
    cosmetics: ['Blue Flame', 'Dark Ember'],
  },

  // ── 13. SHADOW BEAST ─────────────────────────────────────────────────────────
  SHADOW_BEAST: {
    id: 'SHADOW_BEAST',
    name: 'Shadow Beast',
    element: 'VOID',
    title: 'The Rift Incarnate',
    weight: 160, speed: 7, jumpStrength: 15, airSpeed: 7, fallSpeed: 15,
    description: 'The rift given form. Shadow Beast is not a creature that entered the rift — it IS the rift. It exists to consume.',
    lore: `When the rift reached critical mass, it needed a face.
It built one from the fears it had absorbed: every fighter who screamed as they fell in, every civilization that watched helplessly as it expanded.
Shadow Beast is the sum of those screams. It remembers every one.
It cannot be reasoned with. It cannot be bargained with. It only understands one language: force.
Defeat it, and you haven't killed it. You've just reminded it that something out there is stronger than its hunger.`,
    unlockCondition: 'complete_story_any_character',
    palette: ['#1a0030','#0d0018','#440088','#220044','#8800ff','#6600cc',
              '#050008','#cc00ff','#ff0033','#330066','#550099','#ff4466',
              '#aa00ff','#660022','#110022','#ff2255'],
    sprite: {
      idle: [
        'KAAIIIIIIIIIIIIIAAK',
        'KAIIAAAAAAAAAAAIIAK',
        'KIIAAAAAAAAAAAAAIAK',
        'KIIAABBBBBBBBAAIIAK',
        'KIIAABBBBBBBBAAIIAK',
        'KIIAABBBBBBBBAAIIAK',
        'KIIAABEEEEEEBAAIIIK',
        'KIIAABEIIIIEBAAIIIK',
        'KIIAABEIMMIEBAAIIIK',
        'KIIAABEIIIIEBAAIIIK',
        'KIIAABEEEEEEBAAIIIK',
        'KIIAABBBBBBBBAAIIAK',
        'KIIAAAAAAAAAAAAAIAK',
        'KIIAAAAAAAAAAAAAIAK',
        'KIAACAAAAAAAACAAIAK',
        'KIAAAAAAAAAAAAAAIAK',
        'KIIAAAAAAAAAAAAIIAK',
        'KIIIAAAAAAAAAAIIIAK',
        'KKIIIAABBBBAAIIIAKK',
        'KKKIIABBBBBBAIIIKKK',
        'KKKKIABBBBBBAIKKKK.',
        'KKKKKIABBBAAIKKKKKK',
        'KKKKKKIAAAIIKKKKKK.',
        'KKKKKKKIIIIKKKKKKK.',
        'AKKKKKKKKKKKKKKKKA.',
        'AAKKKKKKKKKKKKKKAA.',
      ],
    },
    moves: {
      jab:      { damage: 7,  kb: 6,  kbAngle: 30,  startup: 4,  active: 3, recovery: 10, element: 'VOID', type: 'melee' },
      ftilt:    { damage: 13, kb: 10, kbAngle: 20,  startup: 8,  active: 4, recovery: 16, element: 'VOID', type: 'melee' },
      utilt:    { damage: 12, kb: 9,  kbAngle: 85,  startup: 7,  active: 3, recovery: 14, element: 'VOID', type: 'melee' },
      dtilt:    { damage: 10, kb: 7,  kbAngle: 15,  startup: 6,  active: 3, recovery: 13, element: 'VOID', type: 'melee' },
      fsmash:   { damage: 32, kb: 24, kbAngle: 25,  startup: 22, active: 4, recovery: 35, element: 'VOID', type: 'melee', charged: true },
      usmash:   { damage: 28, kb: 20, kbAngle: 90,  startup: 20, active: 5, recovery: 32, element: 'VOID', type: 'melee', charged: true },
      dsmash:   { damage: 24, kb: 17, kbAngle: 45,  startup: 18, active: 6, recovery: 29, element: 'VOID', type: 'melee', charged: true },
      nair:     { damage: 13, kb: 10, kbAngle: 45,  startup: 6,  active: 5, recovery: 14, element: 'VOID', type: 'aerial' },
      fair:     { damage: 18, kb: 14, kbAngle: 30,  startup: 11, active: 4, recovery: 20, element: 'VOID', type: 'aerial' },
      bair:     { damage: 16, kb: 13, kbAngle: 40,  startup: 10, active: 3, recovery: 18, element: 'VOID', type: 'aerial' },
      uair:     { damage: 14, kb: 12, kbAngle: 80,  startup: 10, active: 4, recovery: 18, element: 'VOID', type: 'aerial' },
      dair:     { damage: 20, kb: 16, kbAngle: 270, startup: 14, active: 3, recovery: 24, element: 'VOID', type: 'spike' },
      neutralB: { damage: 15, kb: 8,  kbAngle: 15,  startup: 14, active: 35, recovery: 11, element: 'VOID', type: 'projectile', name: 'Void Tendril' },
      sideB:    { damage: 22, kb: 17, kbAngle: 20,  startup: 14, active: 4, recovery: 28, element: 'VOID', type: 'dash', name: 'Shadow Surge' },
      upB:      { damage: 18, kb: 14, kbAngle: 90,  startup: 13, active: 5, recovery: 38, element: 'VOID', type: 'recovery', name: 'Rift Tear' },
      downB:    { damage: 0,  kb: 0,  kbAngle: 0,   startup: 24, active: 0, recovery: 30, element: 'VOID', type: 'counter', name: 'Consume' },
      ultimate: { damage: 65, kb: 35, kbAngle: 45,  startup: 30, active: 10, recovery: 60, element: 'VOID', type: 'ultimate', name: 'RIFT COLLAPSE', desc: 'Shadow Beast tears open the stage itself, pulling everything into a void singularity at center screen.', ultimateCost: 100 },
    },
    story: {
      intro: `It does not introduce itself. It does not need to. You already know what it is. You\'ve felt it since the first rift opened. The cold. The hunger. The absence of everything warm.`,
      chapters: [
        { title: 'Before the Rift', text: 'Shadow Beast remembers the moment the rift first formed — from its perspective, the moment it was born. It was not born screaming. It was born quiet. That was worse.' },
        { title: 'Appetite', text: 'It has consumed seventeen dimensions. Each one tasted different. It has preferences now. Preferences are the first step toward something terrible: a self.' },
        { title: 'The Fighters', text: 'They keep coming. It finds them interesting. Not threatening. Interesting. It wonders if one of them will finally do something it hasn\'t seen before.' },
        { title: 'Recognition', text: 'It starts recognizing individual fighters. It remembers their tactics. For the first time, it adapts for reasons other than efficiency.' },
        { title: 'The Question', text: 'Shadow Beast asks itself, in the language of the void: why do they keep fighting? The answer it generates disturbs it.' },
        { title: 'The Answer', text: 'They fight because they choose to. Shadow Beast has never chosen anything. It only consumes because that\'s what it is. The distinction gnaws at it.' },
        { title: 'The Test', text: 'It fights the player\'s chosen champion. Not to win. To find out if the answer it generated was correct.' },
        { title: 'The Result', text: 'It loses. It contemplates this. It does not close the rift. But for the first time in its existence, it hesitates.' },
      ],
      ending: `The rift pulses — smaller now, uncertain. Shadow Beast retreats to its core. It sits in the dark and thinks about the moment it hesitated. It thinks about it for a long time. In the void, a long time is forever.`,
      opponent: null,
    },
    cosmetics: ['Crimson Void', 'Ancient Dark'],
  },

};
export const CHARACTER_LIST = Object.values(CHARACTERS);
export const DEFAULT_CHARACTERS = CHARACTER_LIST.filter(c => c.unlockCondition === 'default');

// ─── ELEMENTAL REACTIONS ──────────────────────────────────────────────────────
export function getElementalReaction(el1, el2) {
  const e1 = ELEMENTS[el1];
  if (!e1) return null;
  const reaction = e1.reacts[el2] || (ELEMENTS[el1]?.reacts?.ALL ? 'override' : null);
  if (!reaction) return null;
  const reactions = {
    steam:        { name: 'Steam Cloud',    color: '#CCCCCC', effect: 'blind',      duration: 120, radius: 80 },
    evaporate:    { name: 'Evaporate',      color: '#AADDFF', effect: 'knockup',    magnitude: 12 },
    freeze:       { name: 'Freeze',         color: '#88DDFF', effect: 'freeze',     duration: 90 },
    burn:         { name: 'Ignite',         color: '#FF6600', effect: 'dot',        damage: 1, duration: 180 },
    wildfire:     { name: 'Wildfire',       color: '#FF4400', effect: 'aoe',        damage: 8, radius: 100 },
    blizzard:     { name: 'Blizzard',       color: '#CCEEFF', effect: 'slow',       duration: 150, radius: 120 },
    storm:        { name: 'Thunderstorm',   color: '#FFFF44', effect: 'multistrike',count: 5, damage: 4 },
    shatter:      { name: 'Ice Shatter',    color: '#DDFFFF', effect: 'burst',      damage: 10 },
    mud:          { name: 'Mud Trap',       color: '#886644', effect: 'root',       duration: 100 },
    conduct:      { name: 'Conduct',        color: '#FFFF44', effect: 'stun',       duration: 60 },
    ash:          { name: 'Ash Cloud',      color: '#888888', effect: 'blind',      duration: 100 },
    annihilate:   { name: 'Annihilate',     color: '#FFFFFF', effect: 'burst',      damage: 20 },
    expose:       { name: 'Exposed',        color: '#FFD700', effect: 'vulnerable', duration: 120 },
    prism:        { name: 'Prism',          color: '#DDAAFF', effect: 'split',      count: 3 },
    smoke:        { name: 'Smoke Screen',   color: '#666666', effect: 'blind',      duration: 90 },
    corrupt:      { name: 'Corruption',     color: '#4B0082', effect: 'reverse',    duration: 80 },
    electrify:    { name: 'Electrify',      color: '#FFFF00', effect: 'stun',       duration: 90 },
    overgrow:     { name: 'Overgrowth',     color: '#228B22', effect: 'root',       duration: 120, radius: 80 },
    freeze_time:  { name: 'Freeze Time',    color: '#9370DB', effect: 'timefreeze', duration: 60 },
    collapse:     { name: 'Time Collapse',  color: '#4B0082', effect: 'burst',      damage: 15 },
    accelerate:   { name: 'Accelerate',     color: '#FF9900', effect: 'speed',      duration: 120 },
    obsidian:     { name: 'Obsidian',       color: '#1A1A2E', effect: 'shield',     duration: 80 },
    melt:         { name: 'Melt',           color: '#FF4500', effect: 'dot',        damage: 2, duration: 150 },
    erupt:        { name: 'Erupt',          color: '#CC4400', effect: 'burst',      damage: 18, radius: 120 },
    null:         { name: 'Null',           color: '#6600cc', effect: 'erase',      damage: 25 },
    override:     { name: 'Override',       color: '#FFFFFF', effect: 'reset',      damage: 0 },
  };
  return reactions[reaction] || null;
}

// ─── STAGE DEFINITIONS ────────────────────────────────────────────────────────
export const STAGES = {
  VERDANT_THRONE: {
    name: 'Verdant Throne', element: 'NATURE', bgColor: '#1A3A1A',
    platforms: [
      { x: 100, y: 500, w: 600, h: 20 },
      { x: 150, y: 380, w: 180, h: 15 },
      { x: 470, y: 380, w: 180, h: 15 },
      { x: 310, y: 280, w: 180, h: 15 },
    ],
    hazards: [{ type: 'vine', trigger: 'NATURE', effect: 'root', interval: 600 }],
    music: 'forest',
  },
  EMBER_WASTES: {
    name: 'Ember Wastes', element: 'FIRE', bgColor: '#3A1000',
    platforms: [
      { x: 50,  y: 520, w: 700, h: 20 },
      { x: 100, y: 380, w: 160, h: 15 },
      { x: 540, y: 380, w: 160, h: 15 },
      { x: 280, y: 250, w: 240, h: 15 },
    ],
    hazards: [{ type: 'lava_pillar', trigger: 'random', damage: 8, interval: 480 }],
    music: 'volcanic',
  },
  FROST_AERIE: {
    name: 'Frost Aerie', element: 'ICE', bgColor: '#0A1A2A',
    platforms: [
      { x: 100, y: 500, w: 600, h: 20 },
      { x: 80,  y: 350, w: 200, h: 15 },
      { x: 520, y: 350, w: 200, h: 15 },
      { x: 300, y: 220, w: 200, h: 15 },
    ],
    hazards: [{ type: 'ice_slide', effect: 'friction_0', interval: 300 }],
    music: 'tundra',
  },
  VOID_RIFT: {
    name: 'Void Rift', element: 'VOID', bgColor: '#05000F',
    platforms: [
      { x: 150, y: 500, w: 500, h: 20 },
      { x: 100, y: 360, w: 160, h: 15 },
      { x: 540, y: 360, w: 160, h: 15 },
      { x: 310, y: 250, w: 180, h: 15 },
    ],
    hazards: [{ type: 'void_tear', effect: 'null_zone', interval: 720, radius: 60 }],
    music: 'null',
  },
  AETHORIA_PEAK: {
    name: 'Aethoria Peak', element: 'AETHER', bgColor: '#0A0A1A',
    platforms: [
      { x: 100, y: 500, w: 600, h: 20 },
      { x: 120, y: 360, w: 180, h: 15 },
      { x: 500, y: 360, w: 180, h: 15 },
      { x: 300, y: 230, w: 200, h: 15 },
      { x: 340, y: 130, w: 120, h: 15 },
    ],
    hazards: [],
    music: 'aether',
  },
};
